/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Instalacao;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-18T00:44:08.387Z")

@Validated
@Api(value = "instalacao-cliente", description = "the instalacao-cliente API")
@RequestMapping(value = "")
public interface InstalacaoClienteApi {

    @ApiOperation(value = "Busca Instalação por CPF", nickname = "buscaInstalacaoPorCpf", notes = "", response = Instalacao.class, tags={ "Instalação", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Instalacao.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Fatura not found") })
    @RequestMapping(value = "/instalacao-cliente/{cpf}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Instalacao> buscaInstalacaoPorCpf(@ApiParam(value = "",required=true) @PathVariable("cpf") Long cpf);

}
