/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Instalacao;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-18T00:44:08.387Z")

@Validated
@Api(value = "instalacao", description = "the instalacao API")
@RequestMapping(value = "")
public interface InstalacaoApi {

    @ApiOperation(value = "Adicionar uma nova Instalação", nickname = "addInstalacao", notes = "", tags={ "Instalação", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/instalacao",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addInstalacao(@ApiParam(value = "Adicionar Instalação" ,required=true )  @Valid @RequestBody Instalacao body);


    @ApiOperation(value = "Busca Instalação por Código", nickname = "buscaInstalacaoPorCodigo", notes = "", response = Instalacao.class, tags={ "Instalação", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Instalacao.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Instalacao not found") })
    @RequestMapping(value = "/instalacao/{codigo}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Instalacao> buscaInstalacaoPorCodigo(@ApiParam(value = "",required=true) @PathVariable("codigo") Long codigo);


    @ApiOperation(value = "Buscar todos as Instalação", nickname = "buscaTodasInstalacao", notes = "", response = Instalacao.class, tags={ "Instalação", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Instalacao.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Instalacao not found") })
    @RequestMapping(value = "/instalacao",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Instalacao> buscaTodasInstalacao();

}
